_target_: addiagnosis.modules.barlow_twins.Barlow_Twins_Module
lr: 0.5
weight_decay: 1.5e-6
pretrained_model: null
batch_size: 64
encoder_out_dim: 512
z_dim: 2048
lambda_coeff: 0.005
warmup_epochs: 10

net:
  _target_: addiagnosis.models.resnet.SingleResNet
  in_channels: 1
  n_blocks: 6
  bn_momentum: 0.05
  n_basefilters: 16
  dropout_rate: 0.1
  resnet_version: 'base' 
  remain_downsample_steps: null
  