_target_: addiagnosis.modules.transfer_learning_diagnosis.Transfer_Learning_DiagnosisModule
pretrained_model: /path/checkpoints/last.ckpt
lr: 0.0005
weight_decay: 0.00001
out_class_num: 3

net:
  _target_: addiagnosis.models.resnet.SingleResNet
  in_channels: 1
  n_outputs: 3
  n_blocks: 6
  bn_momentum: 0.05
  n_basefilters: 16
  dropout_rate: 0.1
  resnet_version: 'base' 
  remain_downsample_steps: null
  num_mlp: 2
  no_downsample: False
