# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: task_data.yaml
  - model: transfer_learning.yaml
  - logger: tensorboard.yaml
  - trainer: default_transfer.yaml

# path to folder with data
data_dir: /path/to/data

# seed for random number generators in pytorch, numpy and python.random
seed: 0

name: "test_TripletTraining"

# passing checkpoint dir is necessary
ckpt_path: /path/to/ckpt
early_stop: True # using the best-val-bacc model for testing