# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - callbacks: default.yaml
  - datamodule: adni_nifd.yaml
          # uk_biobank.yaml  => self-supervised learning
          # adni_nifd.yaml   => self-distillation
  - model: self_distillation.yaml
          # barlow.yaml
          # self_distillation.yaml
          # dira.yaml
          # vicreg.yaml
          # SupCon.yaml
  - logger: tensorboard.yaml
  - trainer: default.yaml

# path to folder with data
data_dir: /path/to/data

# seed for random number generators in pytorch, numpy and python.random
seed: 0

# default name for the experiment, determines logging folder path
name: "Barlow_TripletTraining"