# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - callbacks: default_transfer.yaml
  - datamodule: task_data.yaml
  - model: transfer_learning.yaml
  - logger: tensorboard.yaml
  - trainer: default_transfer.yaml

# path to folder with data
data_dir: /path/to/data

# seed for random number generators in pytorch, numpy and python.random
seed: 0

# default name for the experiment, determines logging folder path
name: "Transfer_learning" 